// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_AVATARMENU_H
#define UI_AVATARMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AvatarMenu
extern void ui_AvatarMenu_screen_init(void);
extern void ui_AvatarMenu_screen_destroy(void);
extern void ui_event_AvatarMenu(lv_event_t * e);
extern lv_obj_t * ui_AvatarMenu;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_AvatarPanel;
extern lv_obj_t * ui_AvatarsImage3;
extern void ui_event_PhoenyUserBtn1(lv_event_t * e);
extern lv_obj_t * ui_PhoenyUserBtn1;
extern void ui_event_LizzyUserBtn1(lv_event_t * e);
extern lv_obj_t * ui_LizzyUserBtn1;
extern void ui_event_PuppyUseBtn1(lv_event_t * e);
extern lv_obj_t * ui_PuppyUseBtn1;
extern void ui_event_KittyUserBtn1(lv_event_t * e);
extern lv_obj_t * ui_KittyUserBtn1;
extern lv_obj_t * ui_AvatarsImage4;
extern void ui_event_PiggyUserBtn1(lv_event_t * e);
extern lv_obj_t * ui_PiggyUserBtn1;
extern void ui_event_FroggyUserBtn1(lv_event_t * e);
extern lv_obj_t * ui_FroggyUserBtn1;
extern void ui_event_HorsyUserBtn1(lv_event_t * e);
extern lv_obj_t * ui_HorsyUserBtn1;
extern void ui_event_PandyUserBtn1(lv_event_t * e);
extern lv_obj_t * ui_PandyUserBtn1;
extern lv_obj_t * ui_AvatarMenuLabel;
extern lv_obj_t * ui_AvatarUpdateSuccessImage;
// CUSTOM VARIABLES
extern lv_obj_t * uic_AvatarMenu;
extern lv_obj_t * uic_AvatarPanel;
extern lv_obj_t * uic_AvatarMenuLabel;
extern lv_obj_t * uic_AvatarUpdateSuccessImage;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

