// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_AVATARMENU_H
#define UI_AVATARMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AvatarMenu
extern void ui_AvatarMenu_screen_init(void);
extern void ui_AvatarMenu_screen_destroy(void);
extern void ui_event_AvatarMenu(lv_event_t * e);
extern lv_obj_t * ui_AvatarMenu;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_AvatarPanel;
extern lv_obj_t * ui_AvatarsImage2;
extern void ui_event_PhoenyUserBtn(lv_event_t * e);
extern lv_obj_t * ui_PhoenyUserBtn;
extern void ui_event_LizzyUserBtn(lv_event_t * e);
extern lv_obj_t * ui_LizzyUserBtn;
extern void ui_event_PuppyUseBtn(lv_event_t * e);
extern lv_obj_t * ui_PuppyUseBtn;
extern void ui_event_KittyUserBtn(lv_event_t * e);
extern lv_obj_t * ui_KittyUserBtn;
extern lv_obj_t * ui_AvatarsImage1;
extern void ui_event_PiggyUserBtn(lv_event_t * e);
extern lv_obj_t * ui_PiggyUserBtn;
extern void ui_event_FroggyUserBtn(lv_event_t * e);
extern lv_obj_t * ui_FroggyUserBtn;
extern void ui_event_HorsyUserBtn(lv_event_t * e);
extern lv_obj_t * ui_HorsyUserBtn;
extern void ui_event_PandyUserBtn(lv_event_t * e);
extern lv_obj_t * ui_PandyUserBtn;
extern lv_obj_t * ui_AvatarMenuLabel;
extern lv_obj_t * ui_AvatarUpdateSuccessImage;
// CUSTOM VARIABLES
extern lv_obj_t * uic_AvatarMenu;
extern lv_obj_t * uic_AvatarPanel;
extern lv_obj_t * uic_AvatarsImage2;
extern lv_obj_t * uic_PhoenyUserBtn;
extern lv_obj_t * uic_LizzyUserBtn;
extern lv_obj_t * uic_PuppyUseBtn;
extern lv_obj_t * uic_KittyUserBtn;
extern lv_obj_t * uic_AvatarsImage1;
extern lv_obj_t * uic_PiggyUserBtn;
extern lv_obj_t * uic_FroggyUserBtn;
extern lv_obj_t * uic_HorsyUserBtn;
extern lv_obj_t * uic_PandyUserBtn;
extern lv_obj_t * uic_AvatarMenuLabel;
extern lv_obj_t * uic_AvatarUpdateSuccessImage;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

