// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_AVATARSCREEN_H
#define UI_AVATARSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AvatarScreen
extern void ui_AvatarScreen_screen_init(void);
extern void ui_AvatarScreen_screen_destroy(void);
extern void ui_event_AvatarScreen(lv_event_t * e);
extern lv_obj_t * ui_AvatarScreen;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_AvatarScreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

