// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "../ui.h"

lv_obj_t * uic_AvatarUpdateSuccessImage;
lv_obj_t * uic_AvatarMenuLabel;
lv_obj_t * uic_AvatarPanel;
lv_obj_t * uic_AvatarMenu;
lv_obj_t * ui_AvatarMenu;
lv_obj_t * ui_Image9;
lv_obj_t * ui_AvatarPanel;
lv_obj_t * ui_AvatarsImage3;
lv_obj_t * ui_PhoenyUserBtn1;
lv_obj_t * ui_LizzyUserBtn1;
lv_obj_t * ui_PuppyUseBtn1;
lv_obj_t * ui_KittyUserBtn1;
lv_obj_t * ui_AvatarsImage4;
lv_obj_t * ui_PiggyUserBtn1;
lv_obj_t * ui_FroggyUserBtn1;
lv_obj_t * ui_HorsyUserBtn1;
lv_obj_t * ui_PandyUserBtn1;
lv_obj_t * ui_AvatarMenuLabel;
lv_obj_t * ui_AvatarUpdateSuccessImage;

// event funtions
void ui_event_AvatarMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_PhoenyUserBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ChangeUserPhoeny(e);
        (e);
    }
}

void ui_event_LizzyUserBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ChangeUserLizzy(e);
    }
}

void ui_event_PuppyUseBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ChangeUserPuppy(e);
        (e);
    }
}

void ui_event_KittyUserBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ChangeUserKitty(e);
        (e);
    }
}

void ui_event_PiggyUserBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ChangeUserPiggy(e);
        (e);
    }
}

void ui_event_FroggyUserBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ChangeUserFroggy(e);
    }
}

void ui_event_HorsyUserBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ChangeUserHorsy(e);
        (e);
    }
}

void ui_event_PandyUserBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ChangeUserPandy(e);
        (e);
    }
}

// build funtions

void ui_AvatarMenu_screen_init(void)
{
    ui_AvatarMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AvatarMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AvatarMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AvatarMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_AvatarMenu);
    lv_img_set_src(ui_Image9, &ui_img_whitepanel_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AvatarPanel = lv_obj_create(ui_AvatarMenu);
    lv_obj_set_width(ui_AvatarPanel, 240);
    lv_obj_set_height(ui_AvatarPanel, 190);
    lv_obj_set_x(ui_AvatarPanel, 0);
    lv_obj_set_y(ui_AvatarPanel, 20);
    lv_obj_set_align(ui_AvatarPanel, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_AvatarPanel, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_AvatarPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AvatarPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AvatarPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AvatarPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_AvatarPanel, lv_color_hex(0xFFA300), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AvatarPanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_AvatarsImage3 = lv_img_create(ui_AvatarPanel);
    lv_img_set_src(ui_AvatarsImage3, &ui_img_profiles2_png);
    lv_obj_set_width(ui_AvatarsImage3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AvatarsImage3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AvatarsImage3, 0);
    lv_obj_set_y(ui_AvatarsImage3, -10);
    lv_obj_set_align(ui_AvatarsImage3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AvatarsImage3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AvatarsImage3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PhoenyUserBtn1 = lv_btn_create(ui_AvatarsImage3);
    lv_obj_set_width(ui_PhoenyUserBtn1, 60);
    lv_obj_set_height(ui_PhoenyUserBtn1, 60);
    lv_obj_set_x(ui_PhoenyUserBtn1, 40);
    lv_obj_set_y(ui_PhoenyUserBtn1, -25);
    lv_obj_set_align(ui_PhoenyUserBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PhoenyUserBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PhoenyUserBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PhoenyUserBtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PhoenyUserBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LizzyUserBtn1 = lv_btn_create(ui_AvatarsImage3);
    lv_obj_set_width(ui_LizzyUserBtn1, 60);
    lv_obj_set_height(ui_LizzyUserBtn1, 60);
    lv_obj_set_x(ui_LizzyUserBtn1, -42);
    lv_obj_set_y(ui_LizzyUserBtn1, -25);
    lv_obj_set_align(ui_LizzyUserBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LizzyUserBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LizzyUserBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LizzyUserBtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LizzyUserBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PuppyUseBtn1 = lv_btn_create(ui_AvatarsImage3);
    lv_obj_set_width(ui_PuppyUseBtn1, 60);
    lv_obj_set_height(ui_PuppyUseBtn1, 60);
    lv_obj_set_x(ui_PuppyUseBtn1, -42);
    lv_obj_set_y(ui_PuppyUseBtn1, 60);
    lv_obj_set_align(ui_PuppyUseBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PuppyUseBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PuppyUseBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PuppyUseBtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PuppyUseBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KittyUserBtn1 = lv_btn_create(ui_AvatarsImage3);
    lv_obj_set_width(ui_KittyUserBtn1, 60);
    lv_obj_set_height(ui_KittyUserBtn1, 60);
    lv_obj_set_x(ui_KittyUserBtn1, 40);
    lv_obj_set_y(ui_KittyUserBtn1, 60);
    lv_obj_set_align(ui_KittyUserBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KittyUserBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_KittyUserBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_KittyUserBtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KittyUserBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AvatarsImage4 = lv_img_create(ui_AvatarPanel);
    lv_img_set_src(ui_AvatarsImage4, &ui_img_profiles_png);
    lv_obj_set_width(ui_AvatarsImage4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AvatarsImage4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AvatarsImage4, 0);
    lv_obj_set_y(ui_AvatarsImage4, 155);
    lv_obj_set_align(ui_AvatarsImage4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AvatarsImage4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AvatarsImage4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PiggyUserBtn1 = lv_btn_create(ui_AvatarsImage4);
    lv_obj_set_width(ui_PiggyUserBtn1, 60);
    lv_obj_set_height(ui_PiggyUserBtn1, 60);
    lv_obj_set_x(ui_PiggyUserBtn1, 40);
    lv_obj_set_y(ui_PiggyUserBtn1, -25);
    lv_obj_set_align(ui_PiggyUserBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PiggyUserBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PiggyUserBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PiggyUserBtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PiggyUserBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FroggyUserBtn1 = lv_btn_create(ui_AvatarsImage4);
    lv_obj_set_width(ui_FroggyUserBtn1, 60);
    lv_obj_set_height(ui_FroggyUserBtn1, 60);
    lv_obj_set_x(ui_FroggyUserBtn1, -42);
    lv_obj_set_y(ui_FroggyUserBtn1, -25);
    lv_obj_set_align(ui_FroggyUserBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FroggyUserBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FroggyUserBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FroggyUserBtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FroggyUserBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HorsyUserBtn1 = lv_btn_create(ui_AvatarsImage4);
    lv_obj_set_width(ui_HorsyUserBtn1, 60);
    lv_obj_set_height(ui_HorsyUserBtn1, 60);
    lv_obj_set_x(ui_HorsyUserBtn1, -42);
    lv_obj_set_y(ui_HorsyUserBtn1, 55);
    lv_obj_set_align(ui_HorsyUserBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HorsyUserBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HorsyUserBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HorsyUserBtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HorsyUserBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PandyUserBtn1 = lv_btn_create(ui_AvatarsImage4);
    lv_obj_set_width(ui_PandyUserBtn1, 60);
    lv_obj_set_height(ui_PandyUserBtn1, 60);
    lv_obj_set_x(ui_PandyUserBtn1, 40);
    lv_obj_set_y(ui_PandyUserBtn1, 55);
    lv_obj_set_align(ui_PandyUserBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PandyUserBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PandyUserBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PandyUserBtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PandyUserBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AvatarMenuLabel = lv_label_create(ui_AvatarMenu);
    lv_obj_set_width(ui_AvatarMenuLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AvatarMenuLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AvatarMenuLabel, 0);
    lv_obj_set_y(ui_AvatarMenuLabel, -95);
    lv_obj_set_align(ui_AvatarMenuLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AvatarMenuLabel, "Pick an avatar");
    lv_obj_set_style_text_font(ui_AvatarMenuLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AvatarUpdateSuccessImage = lv_img_create(ui_AvatarMenu);
    lv_img_set_src(ui_AvatarUpdateSuccessImage, &ui_img_checkmark_png);
    lv_obj_set_width(ui_AvatarUpdateSuccessImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AvatarUpdateSuccessImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AvatarUpdateSuccessImage, 82);
    lv_obj_set_y(ui_AvatarUpdateSuccessImage, -64);
    lv_obj_set_align(ui_AvatarUpdateSuccessImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AvatarUpdateSuccessImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AvatarUpdateSuccessImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_AvatarUpdateSuccessImage, 110);

    lv_obj_add_event_cb(ui_PhoenyUserBtn1, ui_event_PhoenyUserBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LizzyUserBtn1, ui_event_LizzyUserBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PuppyUseBtn1, ui_event_PuppyUseBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KittyUserBtn1, ui_event_KittyUserBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PiggyUserBtn1, ui_event_PiggyUserBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FroggyUserBtn1, ui_event_FroggyUserBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HorsyUserBtn1, ui_event_HorsyUserBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PandyUserBtn1, ui_event_PandyUserBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AvatarMenu, ui_event_AvatarMenu, LV_EVENT_ALL, NULL);
    uic_AvatarMenu = ui_AvatarMenu;
    uic_AvatarPanel = ui_AvatarPanel;
    uic_AvatarMenuLabel = ui_AvatarMenuLabel;
    uic_AvatarUpdateSuccessImage = ui_AvatarUpdateSuccessImage;

}

void ui_AvatarMenu_screen_destroy(void)
{
    if(ui_AvatarMenu) lv_obj_del(ui_AvatarMenu);

    // NULL screen variables
    uic_AvatarMenu = NULL;
    ui_AvatarMenu = NULL;
    ui_Image9 = NULL;
    uic_AvatarPanel = NULL;
    ui_AvatarPanel = NULL;
    ui_AvatarsImage3 = NULL;
    ui_PhoenyUserBtn1 = NULL;
    ui_LizzyUserBtn1 = NULL;
    ui_PuppyUseBtn1 = NULL;
    ui_KittyUserBtn1 = NULL;
    ui_AvatarsImage4 = NULL;
    ui_PiggyUserBtn1 = NULL;
    ui_FroggyUserBtn1 = NULL;
    ui_HorsyUserBtn1 = NULL;
    ui_PandyUserBtn1 = NULL;
    uic_AvatarMenuLabel = NULL;
    ui_AvatarMenuLabel = NULL;
    uic_AvatarUpdateSuccessImage = NULL;
    ui_AvatarUpdateSuccessImage = NULL;

}
