// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_EMERGENCYMENU_H
#define UI_EMERGENCYMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EmergencyMenu
extern void ui_EmergencyMenu_screen_init(void);
extern void ui_EmergencyMenu_screen_destroy(void);
extern void ui_event_EmergencyMenu(lv_event_t * e);
extern lv_obj_t * ui_EmergencyMenu;
extern void ui_event_EmergencyIconImg(lv_event_t * e);
extern lv_obj_t * ui_EmergencyIconImg;
extern void ui_event_sendEmergencyButton(lv_event_t * e);
extern lv_obj_t * ui_sendEmergencyButton;
extern lv_obj_t * ui_EmergencySuccessImage;
extern lv_obj_t * ui_Holdlabel;
extern lv_obj_t * ui_navimg;
// CUSTOM VARIABLES
extern lv_obj_t * uic_EmergencyMenu;
extern lv_obj_t * uic_EmergencyIconImg;
extern lv_obj_t * uic_sendEmergencyButton;
extern lv_obj_t * uic_Holdlabel;
extern lv_obj_t * uic_navimg;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

