// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_GROUPSMENU_H
#define UI_GROUPSMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GroupsMenu
extern void ui_GroupsMenu_screen_init(void);
extern void ui_GroupsMenu_screen_destroy(void);
extern void ui_event_GroupsMenu(lv_event_t * e);
extern lv_obj_t * ui_GroupsMenu;
extern lv_obj_t * ui_Image5;
extern void ui_event_GroupSelector(lv_event_t * e);
extern lv_obj_t * ui_GroupSelector;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_GroupsMenu;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

