// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "../ui.h"

lv_obj_t * uic_GroupsMenu;
lv_obj_t * ui_GroupsMenu;
lv_obj_t * ui_Image5;
lv_obj_t * ui_GroupSelector;
lv_obj_t * ui_Label6;

// event funtions
void ui_event_GroupsMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_GroupSelector(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        loraChangeGroup(e);
    }
}

// build funtions

void ui_GroupsMenu_screen_init(void)
{
    ui_GroupsMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GroupsMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GroupsMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GroupsMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_GroupsMenu);
    lv_img_set_src(ui_Image5, &ui_img_whitepanel_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GroupSelector = lv_roller_create(ui_GroupsMenu);
    lv_roller_set_options(ui_GroupSelector, "Gr. 1\nGr. 2\nGr. 3\nGr. 4\nGr. 5\nGr. 6\nGr. 7\nGr. 8\nGr. 9\nGr. 10",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_GroupSelector, 200);
    lv_obj_set_height(ui_GroupSelector, 150);
    lv_obj_set_x(ui_GroupSelector, 0);
    lv_obj_set_y(ui_GroupSelector, 15);
    lv_obj_set_align(ui_GroupSelector, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_GroupSelector, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GroupSelector, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GroupSelector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GroupSelector, lv_color_hex(0xFFA300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GroupSelector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GroupSelector, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_GroupSelector, 100, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GroupSelector, lv_color_hex(0xECA21A), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GroupSelector, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_GroupsMenu);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -95);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Pick a Group");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GroupSelector, ui_event_GroupSelector, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GroupsMenu, ui_event_GroupsMenu, LV_EVENT_ALL, NULL);
    uic_GroupsMenu = ui_GroupsMenu;

}

void ui_GroupsMenu_screen_destroy(void)
{
    if(ui_GroupsMenu) lv_obj_del(ui_GroupsMenu);

    // NULL screen variables
    uic_GroupsMenu = NULL;
    ui_GroupsMenu = NULL;
    ui_Image5 = NULL;
    ui_GroupSelector = NULL;
    ui_Label6 = NULL;

}
