// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_IMAGES_H
#define UI_IMAGES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Images
extern void ui_Images_screen_init(void);
extern void ui_Images_screen_destroy(void);
extern lv_obj_t * ui_Images;
extern lv_obj_t * ui_WaveEmojiImg;
extern lv_obj_t * ui_LikeEmojiImg;
extern lv_obj_t * ui_HeartEmojiImg;
extern lv_obj_t * ui_CelebrateEmojiImg;
extern lv_obj_t * ui_FroggyImg;
extern lv_obj_t * ui_PiggyImg;
extern lv_obj_t * ui_HorsyImg;
extern lv_obj_t * ui_PandyImg;
extern lv_obj_t * ui_PhoenyImg;
extern lv_obj_t * ui_LizzyImg;
extern lv_obj_t * ui_PuppyImg;
extern lv_obj_t * ui_KittyImg;
extern lv_obj_t * ui_EmergencyEmojiImg;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Images;
extern lv_obj_t * uic_WaveEmojiImg;
extern lv_obj_t * uic_LikeEmojiImg;
extern lv_obj_t * uic_HeartEmojiImg;
extern lv_obj_t * uic_CelebrateEmojiImg;
extern lv_obj_t * uic_FroggyImg;
extern lv_obj_t * uic_PiggyImg;
extern lv_obj_t * uic_HorsyImg;
extern lv_obj_t * uic_PandyImg;
extern lv_obj_t * uic_PhoenyImg;
extern lv_obj_t * uic_LizzyImg;
extern lv_obj_t * uic_PuppyImg;
extern lv_obj_t * uic_KittyImg;
extern lv_obj_t * uic_EmergencyEmojiImg;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

