// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_MainPanelImg;
extern lv_obj_t * ui_ScrollPanel;
extern void ui_event_PhoneConnectSelectionImg(lv_event_t * e);
extern lv_obj_t * ui_PhoneConnectSelectionImg;
extern void ui_event_SettingsSelectionImg(lv_event_t * e);
extern lv_obj_t * ui_SettingsSelectionImg;
extern lv_obj_t * ui_HomeContainer2;
extern lv_obj_t * ui_GroupNr;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_BatteryLabel;
extern void ui_event_GroupSelectionImg(lv_event_t * e);
extern lv_obj_t * ui_GroupSelectionImg;
extern void ui_event_AvatarSelectionImg(lv_event_t * e);
extern lv_obj_t * ui_AvatarSelectionImg;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_navBallImg;
extern lv_obj_t * ui_CurrentAvatarImage;
extern void ui_event_goToAvatarMenuBtn2(lv_event_t * e);
extern lv_obj_t * ui_goToAvatarMenuBtn2;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MainScreen;
extern lv_obj_t * uic_MainPanelImg;
extern lv_obj_t * uic_ScrollPanel;
extern lv_obj_t * uic_SettingsSelectionImg;
extern lv_obj_t * uic_GroupNr;
extern lv_obj_t * uic_Date;
extern lv_obj_t * uic_Time;
extern lv_obj_t * uic_BatteryLabel;
extern lv_obj_t * uic_GroupSelectionImg;
extern lv_obj_t * uic_AvatarSelectionImg;
extern lv_obj_t * uic_navBallImg;
extern lv_obj_t * uic_CurrentAvatarImage;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

