// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_MESSAGESMENU_H
#define UI_MESSAGESMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MessagesMenu
extern void ui_MessagesMenu_screen_init(void);
extern void ui_MessagesMenu_screen_destroy(void);
extern void ui_event_MessagesMenu(lv_event_t * e);
extern lv_obj_t * ui_MessagesMenu;
extern lv_obj_t * ui_MessageBGIMG;
extern lv_obj_t * ui_MessageSendCheckMark;
extern lv_obj_t * ui_MessagesContainer;
extern lv_obj_t * ui_EmojiWheel;
extern void ui_event_ShowMessageBoxBtn(lv_event_t * e);
extern lv_obj_t * ui_ShowMessageBoxBtn;
extern void ui_event_LikeBtn(lv_event_t * e);
extern lv_obj_t * ui_LikeBtn;
extern void ui_event_WaveBtn(lv_event_t * e);
extern lv_obj_t * ui_WaveBtn;
extern void ui_event_HeartBtn(lv_event_t * e);
extern lv_obj_t * ui_HeartBtn;
extern void ui_event_PartyBtn(lv_event_t * e);
extern lv_obj_t * ui_PartyBtn;
extern lv_obj_t * ui_Keyboard2;
extern void ui_event_DisableMsgBoxBtn(lv_event_t * e);
extern lv_obj_t * ui_DisableMsgBoxBtn;
extern lv_obj_t * ui_Click_To_Cancel;
extern void ui_event_MessageInputBox(lv_event_t * e);
extern lv_obj_t * ui_MessageInputBox;
extern void ui_event_SendMessageButton(lv_event_t * e);
extern lv_obj_t * ui_SendMessageButton;
extern void ui_event_SendBtnLabel(lv_event_t * e);
extern lv_obj_t * ui_SendBtnLabel;
extern lv_obj_t * ui_SendAMessageLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MessagesMenu;
extern lv_obj_t * uic_MessageSendCheckMark;
extern lv_obj_t * uic_MessagesContainer;
extern lv_obj_t * uic_EmojiWheel;
extern lv_obj_t * uic_ShowMessageBoxBtn;
extern lv_obj_t * uic_LikeBtn;
extern lv_obj_t * uic_WaveBtn;
extern lv_obj_t * uic_HeartBtn;
extern lv_obj_t * uic_PartyBtn;
extern lv_obj_t * uic_DisableMsgBoxBtn;
extern lv_obj_t * uic_Click_To_Cancel;
extern lv_obj_t * uic_MessageInputBox;
extern lv_obj_t * uic_SendMessageButton;
extern lv_obj_t * uic_SendBtnLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

