// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "../ui.h"

lv_obj_t * uic_CurrentAvatarImage;
lv_obj_t * uic_GroupNr;
lv_obj_t * uic_Date;
lv_obj_t * uic_Time;
lv_obj_t * uic_HomeBG;
lv_obj_t * uic_MainScreen;
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_HomeBG;
lv_obj_t * ui_Time;
lv_obj_t * ui_Date;
lv_obj_t * ui_GroupNr;
lv_obj_t * ui_CurrentAvatarImage;

// event funtions
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AvatarScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 200, 0, &ui_AvatarScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MessagesMenu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_MessagesMenu_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_EmergencyMenu, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_EmergencyMenu_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 200, 0, &ui_SettingsScreen_screen_init);
    }
}

void ui_event_HomeBG(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AvatarScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_AvatarScreen_screen_init);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeBG = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_HomeBG, &ui_img_ui_png);
    lv_obj_set_width(ui_HomeBG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HomeBG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HomeBG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeBG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HomeBG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Time = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "11:11");
    lv_obj_set_style_text_color(ui_Time, lv_color_hex(0xECA21A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, 0);
    lv_obj_set_y(ui_Date, -40);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "Wed, 11/12");
    lv_obj_set_style_text_align(ui_Date, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Date, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GroupNr = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_GroupNr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GroupNr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GroupNr, 0);
    lv_obj_set_y(ui_GroupNr, 60);
    lv_obj_set_align(ui_GroupNr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GroupNr, "Gr. 1");
    lv_obj_set_style_text_font(ui_GroupNr, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentAvatarImage = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_CurrentAvatarImage, &ui_img_froggy_png);
    lv_obj_set_width(ui_CurrentAvatarImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentAvatarImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentAvatarImage, 85);
    lv_obj_set_y(ui_CurrentAvatarImage, -85);
    lv_obj_set_align(ui_CurrentAvatarImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CurrentAvatarImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CurrentAvatarImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_HomeBG, ui_event_HomeBG, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);
    uic_MainScreen = ui_MainScreen;
    uic_HomeBG = ui_HomeBG;
    uic_Time = ui_Time;
    uic_Date = ui_Date;
    uic_GroupNr = ui_GroupNr;
    uic_CurrentAvatarImage = ui_CurrentAvatarImage;

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    uic_MainScreen = NULL;
    ui_MainScreen = NULL;
    uic_HomeBG = NULL;
    ui_HomeBG = NULL;
    uic_Time = NULL;
    ui_Time = NULL;
    uic_Date = NULL;
    ui_Date = NULL;
    uic_GroupNr = NULL;
    ui_GroupNr = NULL;
    uic_CurrentAvatarImage = NULL;
    ui_CurrentAvatarImage = NULL;

}
