// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_NOTIFICATIONSCREEN_H
#define UI_NOTIFICATIONSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_NotificationScreen
extern void ui_NotificationScreen_screen_init(void);
extern void ui_NotificationScreen_screen_destroy(void);
extern lv_obj_t * ui_NotificationScreen;
extern void ui_event_NotificationContainer(lv_event_t * e);
extern lv_obj_t * ui_NotificationContainer;
extern void ui_event_NotificationOverlayPanel(lv_event_t * e);
extern lv_obj_t * ui_NotificationOverlayPanel;
extern lv_obj_t * ui_HasSentTextLabel;
extern void ui_event_ReceivedMessageLabel(lv_event_t * e);
extern lv_obj_t * ui_ReceivedMessageLabel;
extern void ui_event_ReceivedEmojiImage(lv_event_t * e);
extern lv_obj_t * ui_ReceivedEmojiImage;
extern lv_obj_t * ui_SenderAvatarInNotificationImage;
// CUSTOM VARIABLES
extern lv_obj_t * uic_NotificationScreen;
extern lv_obj_t * uic_NotificationOverlayPanel;
extern lv_obj_t * uic_HasSentTextLabel;
extern lv_obj_t * uic_ReceivedMessageLabel;
extern lv_obj_t * uic_ReceivedEmojiImage;
extern lv_obj_t * uic_SenderAvatarInNotificationImage;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

