// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "../ui.h"

lv_obj_t * uic_ReceivedMessageLabel;
lv_obj_t * uic_NotificationOverlayPanel;
lv_obj_t * uic_NotificationScreen;
lv_obj_t * ui_NotificationScreen;
lv_obj_t * ui_NotificationOverlayPanel;
lv_obj_t * ui_ReceivedMessageLabel;

// event funtions
void ui_event_NotificationOverlayPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        DismissNoticationAnimation_Animation(ui_NotificationOverlayPanel, 0);
    }
}

// build funtions

void ui_NotificationScreen_screen_init(void)
{
    ui_NotificationScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_NotificationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NotificationScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NotificationScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NotificationOverlayPanel = lv_obj_create(ui_NotificationScreen);
    lv_obj_set_width(ui_NotificationOverlayPanel, 200);
    lv_obj_set_height(ui_NotificationOverlayPanel, 120);
    lv_obj_set_x(ui_NotificationOverlayPanel, 0);
    lv_obj_set_y(ui_NotificationOverlayPanel, -50);
    lv_obj_set_align(ui_NotificationOverlayPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NotificationOverlayPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NotificationOverlayPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NotificationOverlayPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReceivedMessageLabel = lv_label_create(ui_NotificationOverlayPanel);
    lv_obj_set_width(ui_ReceivedMessageLabel, 180);
    lv_obj_set_height(ui_ReceivedMessageLabel, 50);
    lv_obj_set_x(ui_ReceivedMessageLabel, 2);
    lv_obj_set_y(ui_ReceivedMessageLabel, 25);
    lv_obj_set_align(ui_ReceivedMessageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReceivedMessageLabel,
                      "TextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextTextText");

    lv_obj_add_event_cb(ui_NotificationOverlayPanel, ui_event_NotificationOverlayPanel, LV_EVENT_ALL, NULL);
    uic_NotificationScreen = ui_NotificationScreen;
    uic_NotificationOverlayPanel = ui_NotificationOverlayPanel;
    uic_ReceivedMessageLabel = ui_ReceivedMessageLabel;

}

void ui_NotificationScreen_screen_destroy(void)
{
    if(ui_NotificationScreen) lv_obj_del(ui_NotificationScreen);

    // NULL screen variables
    uic_NotificationScreen = NULL;
    ui_NotificationScreen = NULL;
    uic_NotificationOverlayPanel = NULL;
    ui_NotificationOverlayPanel = NULL;
    uic_ReceivedMessageLabel = NULL;
    ui_ReceivedMessageLabel = NULL;

}
