// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "../ui.h"

lv_obj_t * uic_PhoneConnectScreen;
lv_obj_t * ui_PhoneConnectScreen;
lv_obj_t * ui_Image6;

// event funtions
void ui_event_PhoneConnectScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_GroupsScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 200, 0, &ui_GroupsScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_PhoneQRMenu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_PhoneQRMenu_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 200, 0, &ui_SettingsScreen_screen_init);
    }
}

// build funtions

void ui_PhoneConnectScreen_screen_init(void)
{
    ui_PhoneConnectScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PhoneConnectScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_PhoneConnectScreen);
    lv_img_set_src(ui_Image6, &ui_img_phoneconnect_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_PhoneConnectScreen, ui_event_PhoneConnectScreen, LV_EVENT_ALL, NULL);
    uic_PhoneConnectScreen = ui_PhoneConnectScreen;

}

void ui_PhoneConnectScreen_screen_destroy(void)
{
    if(ui_PhoneConnectScreen) lv_obj_del(ui_PhoneConnectScreen);

    // NULL screen variables
    uic_PhoneConnectScreen = NULL;
    ui_PhoneConnectScreen = NULL;
    ui_Image6 = NULL;

}
