// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_PHONEQRMENU_H
#define UI_PHONEQRMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PhoneQRMenu
extern void ui_PhoneQRMenu_screen_init(void);
extern void ui_PhoneQRMenu_screen_destroy(void);
extern void ui_event_PhoneQRMenu(lv_event_t * e);
extern lv_obj_t * ui_PhoneQRMenu;
extern lv_obj_t * ui_qrbackimg;
extern lv_obj_t * ui_scanlabel;
extern lv_obj_t * ui_QRContainer;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PhoneQRMenu;
extern lv_obj_t * uic_qrbackimg;
extern lv_obj_t * uic_scanlabel;
extern lv_obj_t * uic_QRContainer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

