// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_PHONECONNECTSCREEN_H
#define UI_PHONECONNECTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PhoneConnectScreen
extern void ui_PhoneConnectScreen_screen_init(void);
extern void ui_PhoneConnectScreen_screen_destroy(void);
extern void ui_event_PhoneConnectScreen(lv_event_t * e);
extern lv_obj_t * ui_PhoneConnectScreen;
extern lv_obj_t * ui_Image6;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PhoneConnectScreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

