// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "../ui.h"

lv_obj_t * ui_PhoneQRMenu;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label4;

// event funtions
void ui_event_PhoneQRMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_PhoneConnectScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_PhoneConnectScreen_screen_init);
    }
}

// build funtions

void ui_PhoneQRMenu_screen_init(void)
{
    ui_PhoneQRMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PhoneQRMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_PhoneQRMenu);
    lv_img_set_src(ui_Image7, &ui_img_whitepanel_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_PhoneQRMenu);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -95);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Scan With App");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PhoneQRMenu, ui_event_PhoneQRMenu, LV_EVENT_ALL, NULL);

}

void ui_PhoneQRMenu_screen_destroy(void)
{
    if(ui_PhoneQRMenu) lv_obj_del(ui_PhoneQRMenu);

    // NULL screen variables
    ui_PhoneQRMenu = NULL;
    ui_Image7 = NULL;
    ui_Label4 = NULL;

}
