// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "../ui.h"

lv_obj_t * uic_QRContainer;
lv_obj_t * uic_scanlabel;
lv_obj_t * uic_qrbackimg;
lv_obj_t * uic_PhoneQRMenu;
lv_obj_t * ui_PhoneQRMenu;
lv_obj_t * ui_qrbackimg;
lv_obj_t * ui_scanlabel;
lv_obj_t * ui_QRContainer;

// event funtions
void ui_event_PhoneQRMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

// build funtions

void ui_PhoneQRMenu_screen_init(void)
{
    ui_PhoneQRMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PhoneQRMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qrbackimg = lv_img_create(ui_PhoneQRMenu);
    lv_img_set_src(ui_qrbackimg, &ui_img_whitepanel_png);
    lv_obj_set_width(ui_qrbackimg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_qrbackimg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_qrbackimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_qrbackimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_qrbackimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scanlabel = lv_label_create(ui_PhoneQRMenu);
    lv_obj_set_width(ui_scanlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scanlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scanlabel, 0);
    lv_obj_set_y(ui_scanlabel, -95);
    lv_obj_set_align(ui_scanlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scanlabel, "Scan With App");
    lv_obj_set_style_text_font(ui_scanlabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QRContainer = lv_obj_create(ui_PhoneQRMenu);
    lv_obj_remove_style_all(ui_QRContainer);
    lv_obj_set_width(ui_QRContainer, 200);
    lv_obj_set_height(ui_QRContainer, 160);
    lv_obj_set_x(ui_QRContainer, 0);
    lv_obj_set_y(ui_QRContainer, 10);
    lv_obj_set_align(ui_QRContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_QRContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_PhoneQRMenu, ui_event_PhoneQRMenu, LV_EVENT_ALL, NULL);
    uic_PhoneQRMenu = ui_PhoneQRMenu;
    uic_qrbackimg = ui_qrbackimg;
    uic_scanlabel = ui_scanlabel;
    uic_QRContainer = ui_QRContainer;

}

void ui_PhoneQRMenu_screen_destroy(void)
{
    if(ui_PhoneQRMenu) lv_obj_del(ui_PhoneQRMenu);

    // NULL screen variables
    uic_PhoneQRMenu = NULL;
    ui_PhoneQRMenu = NULL;
    uic_qrbackimg = NULL;
    ui_qrbackimg = NULL;
    uic_scanlabel = NULL;
    ui_scanlabel = NULL;
    uic_QRContainer = NULL;
    ui_QRContainer = NULL;

}
