// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "../ui.h"

lv_obj_t * uic_SoundCheckBox;
lv_obj_t * uic_VibrationCheckBox;
lv_obj_t * uic_BrightnessSlider;
lv_obj_t * uic_BrightnessLabel;
lv_obj_t * uic_SettingsPanel;
lv_obj_t * uic_settingslabel;
lv_obj_t * uic_stngsbackimg;
lv_obj_t * uic_SettingsMenu;
lv_obj_t * ui_SettingsMenu;
lv_obj_t * ui_stngsbackimg;
lv_obj_t * ui_settingslabel;
lv_obj_t * ui_SettingsPanel;
lv_obj_t * ui_BrightnessLabel;
lv_obj_t * ui_BrightnessSlider;
lv_obj_t * ui_VibrationCheckBox;
lv_obj_t * ui_SoundCheckBox;

// event funtions
void ui_event_SettingsMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_stngsbackimg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_SettingsPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_BrightnessSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeBrightess(e);
    }
}

void ui_event_VibrationCheckBox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        Vibration_Enable(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        Vibration_Disable(e);
    }
}

void ui_event_SoundCheckBox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        Sound_Enable(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        Sound_Disable(e);
    }
}

// build funtions

void ui_SettingsMenu_screen_init(void)
{
    ui_SettingsMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_stngsbackimg = lv_img_create(ui_SettingsMenu);
    lv_img_set_src(ui_stngsbackimg, &ui_img_whitepanel_png);
    lv_obj_set_width(ui_stngsbackimg, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_stngsbackimg, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_stngsbackimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stngsbackimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_stngsbackimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingslabel = lv_label_create(ui_SettingsMenu);
    lv_obj_set_width(ui_settingslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingslabel, 0);
    lv_obj_set_y(ui_settingslabel, -95);
    lv_obj_set_align(ui_settingslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settingslabel, "Settings");
    lv_obj_set_style_text_font(ui_settingslabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsPanel = lv_obj_create(ui_SettingsMenu);
    lv_obj_set_width(ui_SettingsPanel, 200);
    lv_obj_set_height(ui_SettingsPanel, 160);
    lv_obj_set_x(ui_SettingsPanel, 0);
    lv_obj_set_y(ui_SettingsPanel, 10);
    lv_obj_set_align(ui_SettingsPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingsPanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SettingsPanel, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingsPanel, lv_color_hex(0xFFA300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingsPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessLabel = lv_label_create(ui_SettingsPanel);
    lv_obj_set_width(ui_BrightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessLabel, -30);
    lv_obj_set_y(ui_BrightnessLabel, -60);
    lv_obj_set_align(ui_BrightnessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessLabel, "Brightness");
    lv_obj_set_style_text_font(ui_BrightnessLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSlider = lv_slider_create(ui_SettingsPanel);
    lv_slider_set_range(ui_BrightnessSlider, 10, 255);
    lv_slider_set_value(ui_BrightnessSlider, 130, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BrightnessSlider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_BrightnessSlider, 160);
    lv_obj_set_height(ui_BrightnessSlider, 20);
    lv_obj_set_x(ui_BrightnessSlider, 0);
    lv_obj_set_y(ui_BrightnessSlider, -30);
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0x343434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xE09C23), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xFFA300), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_VibrationCheckBox = lv_checkbox_create(ui_SettingsPanel);
    lv_checkbox_set_text(ui_VibrationCheckBox, "Vibration");
    lv_obj_set_width(ui_VibrationCheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VibrationCheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VibrationCheckBox, -15);
    lv_obj_set_y(ui_VibrationCheckBox, 10);
    lv_obj_set_align(ui_VibrationCheckBox, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_VibrationCheckBox, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_VibrationCheckBox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_VibrationCheckBox, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_VibrationCheckBox, lv_color_hex(0xFFA300), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VibrationCheckBox, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SoundCheckBox = lv_checkbox_create(ui_SettingsPanel);
    lv_checkbox_set_text(ui_SoundCheckBox, "Sound");
    lv_obj_set_width(ui_SoundCheckBox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoundCheckBox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoundCheckBox, -27);
    lv_obj_set_y(ui_SoundCheckBox, 50);
    lv_obj_set_align(ui_SoundCheckBox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SoundCheckBox, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_SoundCheckBox, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_SoundCheckBox, lv_color_hex(0xFFA300), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SoundCheckBox, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_stngsbackimg, ui_event_stngsbackimg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrightnessSlider, ui_event_BrightnessSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VibrationCheckBox, ui_event_VibrationCheckBox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SoundCheckBox, ui_event_SoundCheckBox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsPanel, ui_event_SettingsPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsMenu, ui_event_SettingsMenu, LV_EVENT_ALL, NULL);
    uic_SettingsMenu = ui_SettingsMenu;
    uic_stngsbackimg = ui_stngsbackimg;
    uic_settingslabel = ui_settingslabel;
    uic_SettingsPanel = ui_SettingsPanel;
    uic_BrightnessLabel = ui_BrightnessLabel;
    uic_BrightnessSlider = ui_BrightnessSlider;
    uic_VibrationCheckBox = ui_VibrationCheckBox;
    uic_SoundCheckBox = ui_SoundCheckBox;

}

void ui_SettingsMenu_screen_destroy(void)
{
    if(ui_SettingsMenu) lv_obj_del(ui_SettingsMenu);

    // NULL screen variables
    uic_SettingsMenu = NULL;
    ui_SettingsMenu = NULL;
    uic_stngsbackimg = NULL;
    ui_stngsbackimg = NULL;
    uic_settingslabel = NULL;
    ui_settingslabel = NULL;
    uic_SettingsPanel = NULL;
    ui_SettingsPanel = NULL;
    uic_BrightnessLabel = NULL;
    ui_BrightnessLabel = NULL;
    uic_BrightnessSlider = NULL;
    ui_BrightnessSlider = NULL;
    uic_VibrationCheckBox = NULL;
    ui_VibrationCheckBox = NULL;
    uic_SoundCheckBox = NULL;
    ui_SoundCheckBox = NULL;

}
