// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_SETTINGSMENU_H
#define UI_SETTINGSMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsMenu
extern void ui_SettingsMenu_screen_init(void);
extern void ui_SettingsMenu_screen_destroy(void);
extern void ui_event_SettingsMenu(lv_event_t * e);
extern lv_obj_t * ui_SettingsMenu;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_SettingsPanel;
extern lv_obj_t * ui_BrightnessLabel;
extern void ui_event_BrightnessSlider(lv_event_t * e);
extern lv_obj_t * ui_BrightnessSlider;
extern lv_obj_t * ui_SoundVibrationLabel;
extern void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SettingsMenu;
extern lv_obj_t * uic_SettingsPanel;
extern lv_obj_t * uic_BrightnessLabel;
extern lv_obj_t * uic_BrightnessSlider;
extern lv_obj_t * uic_SoundVibrationLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

