// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "../ui.h"

lv_obj_t * uic_SoundVibrationLabel;
lv_obj_t * uic_BrightnessSlider;
lv_obj_t * uic_BrightnessLabel;
lv_obj_t * uic_SettingsPanel;
lv_obj_t * uic_SettingsMenu;
lv_obj_t * ui_SettingsMenu;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Label5;
lv_obj_t * ui_SettingsPanel;
lv_obj_t * ui_BrightnessLabel;
lv_obj_t * ui_BrightnessSlider;
lv_obj_t * ui_SoundVibrationLabel;
lv_obj_t * ui_Dropdown1;

// event funtions
void ui_event_SettingsMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_SettingsScreen_screen_init);
    }
}

void ui_event_BrightnessSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeBrightess(e);
    }
}

void ui_event_Dropdown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeSoundMode(e);
    }
}

// build funtions

void ui_SettingsMenu_screen_init(void)
{
    ui_SettingsMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_SettingsMenu);
    lv_img_set_src(ui_Image17, &ui_img_whitepanel_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_SettingsMenu);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -95);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Settings");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsPanel = lv_obj_create(ui_SettingsMenu);
    lv_obj_set_width(ui_SettingsPanel, 200);
    lv_obj_set_height(ui_SettingsPanel, 160);
    lv_obj_set_x(ui_SettingsPanel, 0);
    lv_obj_set_y(ui_SettingsPanel, 10);
    lv_obj_set_align(ui_SettingsPanel, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SettingsPanel, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingsPanel, lv_color_hex(0xFFA300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingsPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessLabel = lv_label_create(ui_SettingsPanel);
    lv_obj_set_width(ui_BrightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessLabel, -30);
    lv_obj_set_y(ui_BrightnessLabel, -60);
    lv_obj_set_align(ui_BrightnessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessLabel, "Brightness");
    lv_obj_set_style_text_font(ui_BrightnessLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSlider = lv_slider_create(ui_SettingsPanel);
    lv_slider_set_range(ui_BrightnessSlider, 10, 255);
    lv_slider_set_value(ui_BrightnessSlider, 130, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BrightnessSlider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_BrightnessSlider, 160);
    lv_obj_set_height(ui_BrightnessSlider, 20);
    lv_obj_set_x(ui_BrightnessSlider, 0);
    lv_obj_set_y(ui_BrightnessSlider, -30);
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0x343434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xE09C23), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xFFA300), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SoundVibrationLabel = lv_label_create(ui_SettingsPanel);
    lv_obj_set_width(ui_SoundVibrationLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoundVibrationLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoundVibrationLabel, 0);
    lv_obj_set_y(ui_SoundVibrationLabel, 20);
    lv_obj_set_align(ui_SoundVibrationLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SoundVibrationLabel, "Sound & Vibration");
    lv_obj_set_style_text_font(ui_SoundVibrationLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_SettingsPanel);
    lv_dropdown_set_options(ui_Dropdown1, "Vibration\nSilent\nSound/Vibration");
    lv_obj_set_width(ui_Dropdown1, 150);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 0);
    lv_obj_set_y(ui_Dropdown1, 55);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_bg_color(ui_Dropdown1, lv_color_hex(0x343434), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown1, lv_color_hex(0xFFA300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0x222222),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0xFFA300),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BrightnessSlider, ui_event_BrightnessSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsMenu, ui_event_SettingsMenu, LV_EVENT_ALL, NULL);
    uic_SettingsMenu = ui_SettingsMenu;
    uic_SettingsPanel = ui_SettingsPanel;
    uic_BrightnessLabel = ui_BrightnessLabel;
    uic_BrightnessSlider = ui_BrightnessSlider;
    uic_SoundVibrationLabel = ui_SoundVibrationLabel;

}

void ui_SettingsMenu_screen_destroy(void)
{
    if(ui_SettingsMenu) lv_obj_del(ui_SettingsMenu);

    // NULL screen variables
    uic_SettingsMenu = NULL;
    ui_SettingsMenu = NULL;
    ui_Image17 = NULL;
    ui_Label5 = NULL;
    uic_SettingsPanel = NULL;
    ui_SettingsPanel = NULL;
    uic_BrightnessLabel = NULL;
    ui_BrightnessLabel = NULL;
    uic_BrightnessSlider = NULL;
    ui_BrightnessSlider = NULL;
    uic_SoundVibrationLabel = NULL;
    ui_SoundVibrationLabel = NULL;
    ui_Dropdown1 = NULL;

}
