// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "../ui.h"

lv_obj_t * uic_SettingsScreen;
lv_obj_t * ui_SettingsScreen;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Image19;

// event funtions
void ui_event_SettingsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 200, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_PhoneConnectScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 200, 0, &ui_PhoneConnectScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingsMenu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_SettingsMenu_screen_init);
    }
}

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_SettingsScreen);
    lv_img_set_src(ui_Image16, &ui_img_settings_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_img_create(ui_SettingsScreen);
    lv_img_set_src(ui_Image19, &ui_img_phoeny_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_SettingsScreen, ui_event_SettingsScreen, LV_EVENT_ALL, NULL);
    uic_SettingsScreen = ui_SettingsScreen;

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    uic_SettingsScreen = NULL;
    ui_SettingsScreen = NULL;
    ui_Image16 = NULL;
    ui_Image19 = NULL;

}
