// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef _CHIRPYUI_UI_H
#define _CHIRPYUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_MainScreen.h"
#include "screens/ui_NotificationScreen.h"
#include "screens/ui_Images.h"
#include "screens/ui_EmergencyMenu.h"
#include "screens/ui_MessagesMenu.h"
#include "screens/ui_GroupsMenu.h"
#include "screens/ui_AvatarMenu.h"
#include "screens/ui_SettingsMenu.h"
#include "screens/ui_PhoneQRMenu.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * MessageSentSuccessStart_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MessageSentSuccessEnd_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * DismissNotificationAnimation_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MsgBtnExpand_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ScrollUP_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ScrollDown_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_mainpanel_png);    // assets/MainPanel.png
LV_IMG_DECLARE(ui_img_phoneconnectselection_png);    // assets/PhoneConnectSelection.png
LV_IMG_DECLARE(ui_img_settingsselection_png);    // assets/SettingsSelection.png
LV_IMG_DECLARE(ui_img_grselection_png);    // assets/GrSelection.png
LV_IMG_DECLARE(ui_img_avatarselection_png);    // assets/AvatarSelection.png
LV_IMG_DECLARE(ui_img_scroller_png);    // assets/Scroller.png
LV_IMG_DECLARE(ui_img_selected_png);    // assets/Selected.png
LV_IMG_DECLARE(ui_img_froggy_png);    // assets/froggy.png
LV_IMG_DECLARE(ui_img_horizontalnav_png);    // assets/HorizontalNav.png
LV_IMG_DECLARE(ui_img_celebrationemoji_png);    // assets/celebrationEmoji.png
LV_IMG_DECLARE(ui_img_waveemoji_png);    // assets/waveEmoji.png
LV_IMG_DECLARE(ui_img_likeemoji_png);    // assets/likeEmoji.png
LV_IMG_DECLARE(ui_img_heartemoji_png);    // assets/HeartEmoji.png
LV_IMG_DECLARE(ui_img_piggy_png);    // assets/piggy.png
LV_IMG_DECLARE(ui_img_horsy_png);    // assets/horsy.png
LV_IMG_DECLARE(ui_img_pandy_png);    // assets/pandy.png
LV_IMG_DECLARE(ui_img_phoeny_png);    // assets/phoeny.png
LV_IMG_DECLARE(ui_img_lizzy_png);    // assets/lizzy.png
LV_IMG_DECLARE(ui_img_puppy_png);    // assets/puppy.png
LV_IMG_DECLARE(ui_img_kitty_png);    // assets/kitty.png
LV_IMG_DECLARE(ui_img_emergencyemoji_png);    // assets/emergencyEmoji.png
LV_IMG_DECLARE(ui_img_emicon_png);    // assets/EmIcon.png
LV_IMG_DECLARE(ui_img_checkmark_png);    // assets/CheckMark.png
LV_IMG_DECLARE(ui_img_horizontalnnavother_png);    // assets/HorizontalnNavOther.png
LV_IMG_DECLARE(ui_img_messagepanel_png);    // assets/MessagePanel.png
LV_IMG_DECLARE(ui_img_emojismsg_png);    // assets/EmojisMSG.png
LV_IMG_DECLARE(ui_img_whitepanel_png);    // assets/WhitePanel.png
LV_IMG_DECLARE(ui_img_profiles2_png);    // assets/profiles2.png
LV_IMG_DECLARE(ui_img_profiles_png);    // assets/profiles.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
