// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "ui.h"

lv_obj_t * uic_AvatarMenu;
lv_obj_t * ui_AvatarMenu;
lv_obj_t * ui_Image8;

// event funtions
void ui_event_AvatarMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AvatarScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_AvatarScreen_screen_init);
    }
}

// build funtions

void ui_AvatarMenu_screen_init(void)
{
    ui_AvatarMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AvatarMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AvatarMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AvatarMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_AvatarMenu);
    lv_img_set_src(ui_Image8, &ui_img_whitepanel_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_AvatarMenu, ui_event_AvatarMenu, LV_EVENT_ALL, NULL);
    uic_AvatarMenu = ui_AvatarMenu;

}

void ui_AvatarMenu_screen_destroy(void)
{
    if(ui_AvatarMenu) lv_obj_del(ui_AvatarMenu);

    // NULL screen variables
    uic_AvatarMenu = NULL;
    ui_AvatarMenu = NULL;
    ui_Image8 = NULL;

}
