// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "ui.h"

lv_obj_t * uic_EmergencyButton;
lv_obj_t * ui_EmergencyMenu;
lv_obj_t * ui_Image4;
lv_obj_t * ui_EmergencyButton;

// event funtions
void ui_event_EmergencyMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AvatarScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 200, 0, &ui_AvatarScreen_screen_init);
    }
}

void ui_event_EmergencyButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_SHORT_CLICKED) {
        loraEmergency(e);
    }
}

// build funtions

void ui_EmergencyMenu_screen_init(void)
{
    ui_EmergencyMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_EmergencyMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_EmergencyMenu);
    lv_img_set_src(ui_Image4, &ui_img_emergency_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EmergencyButton = lv_btn_create(ui_EmergencyMenu);
    lv_obj_set_width(ui_EmergencyButton, 152);
    lv_obj_set_height(ui_EmergencyButton, 149);
    lv_obj_set_align(ui_EmergencyButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EmergencyButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EmergencyButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EmergencyButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EmergencyButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_EmergencyButton, ui_event_EmergencyButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EmergencyMenu, ui_event_EmergencyMenu, LV_EVENT_ALL, NULL);
    uic_EmergencyButton = ui_EmergencyButton;

}

void ui_EmergencyMenu_screen_destroy(void)
{
    if(ui_EmergencyMenu) lv_obj_del(ui_EmergencyMenu);

    // NULL screen variables
    ui_EmergencyMenu = NULL;
    ui_Image4 = NULL;
    uic_EmergencyButton = NULL;
    ui_EmergencyButton = NULL;

}
