// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void loraSendLike(lv_event_t * e);
void loraSendWave(lv_event_t * e);
void loraSendHeart(lv_event_t * e);
void loraSendParty(lv_event_t * e);
void loraSendMessageFromBox(lv_event_t * e);
void loraEmergency(lv_event_t * e);
void ChangeUserPhoeny(lv_event_t * e);
void ChangeUserLizzy(lv_event_t * e);
void ChangeUserPuppy(lv_event_t * e);
void ChangeUserKitty(lv_event_t * e);
void ChangeUserPiggy(lv_event_t * e);
void ChangeUserFroggy(lv_event_t * e);
void ChangeUserHorsy(lv_event_t * e);
void ChangeUserPandy(lv_event_t * e);
void loraChangeGroup(lv_event_t * e);
void ChangeBrightess(lv_event_t * e);
void ChangeSoundMode(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
