// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "ui.h"
#include "common.h"

void sendLoraTextMsg(lv_event_t * e)
{
	const char *text = lv_textarea_get_text(ui_MessageInputBox);
	common_sendLoraMessage(text);
}

void loraChangeGroup(lv_event_t * e)
{
	// Your code here
}

void loraEmergency(lv_event_t * e)
{
	// Your code here
}

void loraSendLike(lv_event_t * e)
{
	// Your code here
}

void loraSendWave(lv_event_t * e)
{
	// Your code here
}

void loraSendHeart(lv_event_t * e)
{
	// Your code here
}

void loraSendParty(lv_event_t * e)
{
	// Your code here
}

void loraSendMessageFromBox(lv_event_t * e)
{
	// Your code here
}
