// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_GROUPSSCREEN_H
#define UI_GROUPSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GroupsScreen
extern void ui_GroupsScreen_screen_init(void);
extern void ui_GroupsScreen_screen_destroy(void);
extern void ui_event_GroupsScreen(lv_event_t * e);
extern lv_obj_t * ui_GroupsScreen;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_GroupsScreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

