// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "ui.h"

lv_obj_t * uic_GroupsScreen;
lv_obj_t * ui_GroupsScreen;
lv_obj_t * ui_Image2;

// event funtions
void ui_event_GroupsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_GroupsMenu, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_GroupsMenu_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AvatarScreen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 200, 0, &ui_AvatarScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_PhoneConnectScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 200, 0, &ui_PhoneConnectScreen_screen_init);
    }
}

// build funtions

void ui_GroupsScreen_screen_init(void)
{
    ui_GroupsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GroupsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_GroupsScreen);
    lv_img_set_src(ui_Image2, &ui_img_groups_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_GroupsScreen, ui_event_GroupsScreen, LV_EVENT_ALL, NULL);
    uic_GroupsScreen = ui_GroupsScreen;

}

void ui_GroupsScreen_screen_destroy(void)
{
    if(ui_GroupsScreen) lv_obj_del(ui_GroupsScreen);

    // NULL screen variables
    uic_GroupsScreen = NULL;
    ui_GroupsScreen = NULL;
    ui_Image2 = NULL;

}
