// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#include "ui.h"

lv_obj_t * uic_SendBtnLabel;
lv_obj_t * uic_SendMessageButton;
lv_obj_t * uic_MessageInputBox;
lv_obj_t * uic_Click_To_Cancel;
lv_obj_t * uic_DisableMsgBoxBtn;
lv_obj_t * uic_PartyBtn;
lv_obj_t * uic_HeartBtn;
lv_obj_t * uic_WaveBtn;
lv_obj_t * uic_LikeBtn;
lv_obj_t * uic_ShowMessageBoxBtn;
lv_obj_t * uic_EmojiWheel;
lv_obj_t * uic_MessagesContainer;
lv_obj_t * uic_MessageSendCheckMark;
lv_obj_t * uic_MessagesMenu;
lv_obj_t * ui_MessagesMenu;
lv_obj_t * ui_MessageBGIMG;
lv_obj_t * ui_MessageSendCheckMark;
lv_obj_t * ui_MessagesContainer;
lv_obj_t * ui_EmojiWheel;
lv_obj_t * ui_ShowMessageBoxBtn;
lv_obj_t * ui_LikeBtn;
lv_obj_t * ui_WaveBtn;
lv_obj_t * ui_HeartBtn;
lv_obj_t * ui_PartyBtn;
lv_obj_t * ui_Keyboard2;
lv_obj_t * ui_DisableMsgBoxBtn;
lv_obj_t * ui_Click_To_Cancel;
lv_obj_t * ui_MessageInputBox;
lv_obj_t * ui_SendMessageButton;
lv_obj_t * ui_SendBtnLabel;

// event funtions
void ui_event_MessagesMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_ShowMessageBoxBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Click_To_Cancel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_SendMessageButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_MessageInputBox, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard2,  ui_MessageInputBox);
        _ui_flag_modify(ui_DisableMsgBoxBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_MessagesContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_textarea_move_cursor(ui_MessageInputBox, UI_MOVE_CURSOR_UP);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_LikeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loraSendLike(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_WaveBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loraSendWave(e);
        (e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_HeartBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loraSendHeart(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_PartyBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loraSendParty(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_DisableMsgBoxBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Click_To_Cancel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ShowMessageBoxBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_MessageInputBox, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SendMessageButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_DisableMsgBoxBtn, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_MessagesContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_MessageInputBox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard2,  ui_MessageInputBox);
        _ui_basic_set_property(ui_MessagesContainer, _UI_BASIC_PROPERTY_POSITION_Y,  -100);
        _ui_flag_modify(ui_Click_To_Cancel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_basic_set_property(ui_MessagesContainer, _UI_BASIC_PROPERTY_POSITION_Y,  0);
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_SendMessageButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_flag_modify(ui_Click_To_Cancel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_INSERT) {
        _ui_state_modify(ui_SendMessageButton, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_SendMessageButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loraSendMessageFromBox(e);
    }
}

void ui_event_SendBtnLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loraSendMessageFromBox(e);
    }
}

// build funtions

void ui_MessagesMenu_screen_init(void)
{
    ui_MessagesMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MessagesMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MessagesMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MessagesMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MessageBGIMG = lv_img_create(ui_MessagesMenu);
    lv_img_set_src(ui_MessageBGIMG, &ui_img_messagepanel_png);
    lv_obj_set_width(ui_MessageBGIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MessageBGIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MessageBGIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MessageBGIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MessageBGIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MessageSendCheckMark = lv_img_create(ui_MessagesMenu);
    lv_img_set_src(ui_MessageSendCheckMark, &ui_img_checkmark_png);
    lv_obj_set_width(ui_MessageSendCheckMark, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MessageSendCheckMark, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MessageSendCheckMark, 86);
    lv_obj_set_y(ui_MessageSendCheckMark, -92);
    lv_obj_set_align(ui_MessageSendCheckMark, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MessageSendCheckMark, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MessageSendCheckMark, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_MessageSendCheckMark, 150);

    ui_MessagesContainer = lv_obj_create(ui_MessagesMenu);
    lv_obj_remove_style_all(ui_MessagesContainer);
    lv_obj_set_width(ui_MessagesContainer, 240);
    lv_obj_set_height(ui_MessagesContainer, 240);
    lv_obj_set_align(ui_MessagesContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MessagesContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EmojiWheel = lv_img_create(ui_MessagesContainer);
    lv_img_set_src(ui_EmojiWheel, &ui_img_emojismsg_png);
    lv_obj_set_width(ui_EmojiWheel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EmojiWheel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EmojiWheel, 0);
    lv_obj_set_y(ui_EmojiWheel, 5);
    lv_obj_set_align(ui_EmojiWheel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EmojiWheel, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_EmojiWheel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ShowMessageBoxBtn = lv_btn_create(ui_MessagesContainer);
    lv_obj_set_width(ui_ShowMessageBoxBtn, 48);
    lv_obj_set_height(ui_ShowMessageBoxBtn, 50);
    lv_obj_set_x(ui_ShowMessageBoxBtn, 0);
    lv_obj_set_y(ui_ShowMessageBoxBtn, 36);
    lv_obj_set_align(ui_ShowMessageBoxBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShowMessageBoxBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ShowMessageBoxBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ShowMessageBoxBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShowMessageBoxBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LikeBtn = lv_btn_create(ui_MessagesContainer);
    lv_obj_set_width(ui_LikeBtn, 52);
    lv_obj_set_height(ui_LikeBtn, 50);
    lv_obj_set_x(ui_LikeBtn, -36);
    lv_obj_set_y(ui_LikeBtn, -24);
    lv_obj_set_align(ui_LikeBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LikeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LikeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LikeBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LikeBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaveBtn = lv_btn_create(ui_MessagesContainer);
    lv_obj_set_width(ui_WaveBtn, 52);
    lv_obj_set_height(ui_WaveBtn, 50);
    lv_obj_set_x(ui_WaveBtn, 36);
    lv_obj_set_y(ui_WaveBtn, -25);
    lv_obj_set_align(ui_WaveBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WaveBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WaveBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WaveBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WaveBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartBtn = lv_btn_create(ui_MessagesContainer);
    lv_obj_set_width(ui_HeartBtn, 52);
    lv_obj_set_height(ui_HeartBtn, 50);
    lv_obj_set_x(ui_HeartBtn, -76);
    lv_obj_set_y(ui_HeartBtn, 36);
    lv_obj_set_align(ui_HeartBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HeartBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HeartBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeartBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeartBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PartyBtn = lv_btn_create(ui_MessagesContainer);
    lv_obj_set_width(ui_PartyBtn, 52);
    lv_obj_set_height(ui_PartyBtn, 50);
    lv_obj_set_x(ui_PartyBtn, 75);
    lv_obj_set_y(ui_PartyBtn, 36);
    lv_obj_set_align(ui_PartyBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PartyBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PartyBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PartyBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PartyBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_MessagesMenu);
    lv_obj_set_width(ui_Keyboard2, 240);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 60);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_DisableMsgBoxBtn = lv_btn_create(ui_MessagesMenu);
    lv_obj_set_width(ui_DisableMsgBoxBtn, 230);
    lv_obj_set_height(ui_DisableMsgBoxBtn, 70);
    lv_obj_set_x(ui_DisableMsgBoxBtn, 0);
    lv_obj_set_y(ui_DisableMsgBoxBtn, -82);
    lv_obj_set_align(ui_DisableMsgBoxBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DisableMsgBoxBtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DisableMsgBoxBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DisableMsgBoxBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DisableMsgBoxBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Click_To_Cancel = lv_label_create(ui_MessagesMenu);
    lv_obj_set_width(ui_Click_To_Cancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Click_To_Cancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Click_To_Cancel, 0);
    lv_obj_set_y(ui_Click_To_Cancel, -60);
    lv_obj_set_align(ui_Click_To_Cancel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Click_To_Cancel, "Click here to cancel");
    lv_obj_add_flag(ui_Click_To_Cancel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Click_To_Cancel, lv_color_hex(0x020000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Click_To_Cancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Click_To_Cancel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Click_To_Cancel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MessageInputBox = lv_textarea_create(ui_MessagesMenu);
    lv_obj_set_width(ui_MessageInputBox, 150);
    lv_obj_set_height(ui_MessageInputBox, 35);
    lv_obj_set_x(ui_MessageInputBox, -40);
    lv_obj_set_y(ui_MessageInputBox, -25);
    lv_obj_set_align(ui_MessageInputBox, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_MessageInputBox, "Type a message...");
    lv_obj_add_flag(ui_MessageInputBox, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_SendMessageButton = lv_btn_create(ui_MessagesMenu);
    lv_obj_set_width(ui_SendMessageButton, 70);
    lv_obj_set_height(ui_SendMessageButton, 35);
    lv_obj_set_x(ui_SendMessageButton, 78);
    lv_obj_set_y(ui_SendMessageButton, -25);
    lv_obj_set_align(ui_SendMessageButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_SendMessageButton, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_SendMessageButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SendMessageButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SendMessageButton, lv_color_hex(0xFFA300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SendMessageButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SendMessageButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SendMessageButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SendMessageButton, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SendMessageButton, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SendMessageButton, lv_color_hex(0x855403), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_SendMessageButton, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_color(ui_SendMessageButton, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_SendMessageButton, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_SendBtnLabel = lv_label_create(ui_SendMessageButton);
    lv_obj_set_width(ui_SendBtnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SendBtnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SendBtnLabel, 0);
    lv_obj_set_y(ui_SendBtnLabel, 1);
    lv_obj_set_align(ui_SendBtnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SendBtnLabel, "Send");

    lv_obj_add_event_cb(ui_ShowMessageBoxBtn, ui_event_ShowMessageBoxBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LikeBtn, ui_event_LikeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WaveBtn, ui_event_WaveBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeartBtn, ui_event_HeartBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PartyBtn, ui_event_PartyBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DisableMsgBoxBtn, ui_event_DisableMsgBoxBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MessageInputBox, ui_event_MessageInputBox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SendBtnLabel, ui_event_SendBtnLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SendMessageButton, ui_event_SendMessageButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MessagesMenu, ui_event_MessagesMenu, LV_EVENT_ALL, NULL);
    uic_MessagesMenu = ui_MessagesMenu;
    uic_MessageSendCheckMark = ui_MessageSendCheckMark;
    uic_MessagesContainer = ui_MessagesContainer;
    uic_EmojiWheel = ui_EmojiWheel;
    uic_ShowMessageBoxBtn = ui_ShowMessageBoxBtn;
    uic_LikeBtn = ui_LikeBtn;
    uic_WaveBtn = ui_WaveBtn;
    uic_HeartBtn = ui_HeartBtn;
    uic_PartyBtn = ui_PartyBtn;
    uic_DisableMsgBoxBtn = ui_DisableMsgBoxBtn;
    uic_Click_To_Cancel = ui_Click_To_Cancel;
    uic_MessageInputBox = ui_MessageInputBox;
    uic_SendMessageButton = ui_SendMessageButton;
    uic_SendBtnLabel = ui_SendBtnLabel;

}

void ui_MessagesMenu_screen_destroy(void)
{
    if(ui_MessagesMenu) lv_obj_del(ui_MessagesMenu);

    // NULL screen variables
    uic_MessagesMenu = NULL;
    ui_MessagesMenu = NULL;
    ui_MessageBGIMG = NULL;
    uic_MessageSendCheckMark = NULL;
    ui_MessageSendCheckMark = NULL;
    uic_MessagesContainer = NULL;
    ui_MessagesContainer = NULL;
    uic_EmojiWheel = NULL;
    ui_EmojiWheel = NULL;
    uic_ShowMessageBoxBtn = NULL;
    ui_ShowMessageBoxBtn = NULL;
    uic_LikeBtn = NULL;
    ui_LikeBtn = NULL;
    uic_WaveBtn = NULL;
    ui_WaveBtn = NULL;
    uic_HeartBtn = NULL;
    ui_HeartBtn = NULL;
    uic_PartyBtn = NULL;
    ui_PartyBtn = NULL;
    ui_Keyboard2 = NULL;
    uic_DisableMsgBoxBtn = NULL;
    ui_DisableMsgBoxBtn = NULL;
    uic_Click_To_Cancel = NULL;
    ui_Click_To_Cancel = NULL;
    uic_MessageInputBox = NULL;
    ui_MessageInputBox = NULL;
    uic_SendMessageButton = NULL;
    ui_SendMessageButton = NULL;
    uic_SendBtnLabel = NULL;
    ui_SendBtnLabel = NULL;

}
