// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: ChirpyUI

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern void ui_event_HomeBG(lv_event_t * e);
extern lv_obj_t * ui_HomeBG;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_GroupNr;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MainScreen;
extern lv_obj_t * uic_HomeBG;
extern lv_obj_t * uic_Time;
extern lv_obj_t * uic_Date;
extern lv_obj_t * uic_GroupNr;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

